python run.py -i c1.png -o ./out/o1.png
python run.py -i c2.jpg -o ./out/o2.jpg
python run.py -i c3.png -o ./out/o3.png
python run.py -i c4.png -o ./out/o4.png
python run.py -i c5.png -o ./out/o5.png
python run.py -i c6.png -o ./out/o6.png
python run.py -i c7.png -o ./out/o7.png
python run.py -i c8.jpg -o ./out/o8.jpg
python run.py -i c9.png -o ./out/o9.png
python run.py -i c10.png -o ./out/o10.png
python run.py -i c11.png -o ./out/o11.png
python run.py -i c12.jpg -o ./out/o12.jpg
python run.py -i c13.png -o ./out/o13.png
python run.py -i o14.jpg -o ./out/o14.jpg
python run.py -i card.jpg -o ./out/oCard.jpg
python run.py -i w1.png -o ./out/w1.png
python run.py -i w2.png -o ./out/w2.png
python run.py -i w3.png -o ./out/w3.png
