python run.py -i c1.png -o ./out/o1_01.png
python run.py -i c2.jpg -o ./out/o2_01.jpg
python run.py -i c3.png -o ./out/o3_01.png
python run.py -i c4.png -o ./out/o4_01.png
python run.py -i c5.png -o ./out/o5_01.png
python run.py -i c6.png -o ./out/o6_01.png
python run.py -i c7.png -o ./out/o7_01.png
python run.py -i c8.jpg -o ./out/o8_01.jpg
python run.py -i c9.png -o ./out/o9_01.png
python run.py -i c10.png -o ./out/o10_01.png
python run.py -i c11.png -o ./out/o11_01.png
python run.py -i card.jpg -o ./out/oCard_01.jpg